import jsPDF from 'jspdf';
import { ScanResult } from '@/types';

export function generateClinicalPdfReport(scan: ScanResult, userName = 'Clinician'): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('OCTALYZE CLINICAL SCREENING REPORT', 14, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(224, 83, 60);
  doc.text('Explainable AI-Powered OCT Retinal Analysis', 14, 25);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('REPORT DETAILS', 14, 42);

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 45, 196, 45);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  const reportId = scan.reportNumber || `RPT-OCT-${scan.id}`;
  const dateStr = scan.createdAt ? new Date(scan.createdAt).toLocaleString() : new Date().toLocaleString();

  doc.text(`Report ID: ${reportId}`, 14, 52);
  doc.text(`Scan ID: #${scan.id}`, 80, 52);
  doc.text(`Date & Time: ${dateStr}`, 135, 52);

  doc.text(`Original File: ${scan.originalFilename || 'oct_scan.png'}`, 14, 58);
  doc.text(`Production Model: ${scan.modelName || 'Attention U-Net'}`, 80, 58);
  doc.text(`Clinician: ${userName}`, 135, 58);

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 65, 182, 28, 3, 3, 'FD');

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('AI SCREENING CLASSIFICATION', 20, 73);

  doc.setFontSize(14);
  doc.setTextColor(scan.prediction === 'NORMAL' ? 16 : 225, scan.prediction === 'NORMAL' ? 185 : 29, scan.prediction === 'NORMAL' ? 129 : 72);
  doc.text(`${scan.prediction}`, 20, 83);

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(`Confidence: ${(scan.confidence * 100).toFixed(1)}%`, 80, 83);
  doc.text(`Screening Priority: ${scan.priority}`, 135, 83);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('CLASS PROBABILITY BREAKDOWN', 14, 103);
  doc.line(14, 106, 196, 106);

  const probs = scan.probabilities || { NORMAL: 0, DME: 0, DRUSEN: 0, CNV: 0 };
  const probItems = [
    { label: 'NORMAL', val: (probs.NORMAL * 100).toFixed(1) + '%' },
    { label: 'DME (Diabetic Macular Edema)', val: (probs.DME * 100).toFixed(1) + '%' },
    { label: 'DRUSEN (Sub-RPE Deposits)', val: (probs.DRUSEN * 100).toFixed(1) + '%' },
    { label: 'CNV (Choroidal Neovascularization)', val: (probs.CNV * 100).toFixed(1) + '%' },
  ];

  let yOffset = 113;
  probItems.forEach((item) => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(51, 65, 85);
    doc.text(item.label, 16, yOffset);
    doc.setFont('helvetica', 'bold');
    doc.text(item.val, 175, yOffset, { align: 'right' });
    yOffset += 7;
  });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('EXPLAINABILITY & ATTENTION RATIONALE', 14, 146);
  doc.line(14, 149, 196, 149);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  const findingText = scan.attentionFinding || 'Model spatial attention highlighted prominent structural features in the macular layer.';
  const splitFinding = doc.splitTextToSize(findingText, 180);
  doc.text(splitFinding, 14, 156);

  const descText = scan.description || '';
  if (descText) {
    const splitDesc = doc.splitTextToSize(`Pathology Overview: ${descText}`, 180);
    doc.text(splitDesc, 14, 168);
  }

  if (scan.overlayImage || scan.originalImage) {
    try {
      const imgToUse = scan.overlayImage || scan.originalImage;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('OCT ATTENTION HEATMAP OVERLAY', 14, 185);
      doc.line(14, 188, 196, 188);

      doc.addImage(imgToUse, 'PNG', 55, 193, 100, 65);
    } catch (e) {
      console.warn('Could not embed image into PDF:', e);
    }
  }

  doc.setFillColor(241, 245, 249);
  doc.rect(0, 275, 210, 22, 'F');

  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 116, 139);
  const disclaimer = 'IMPORTANT DISCLAIMER: This screening report is generated by OCTalyze for clinical decision support and research purposes. It does not constitute a certified ophthalmological diagnosis. Clinical correlation by a licensed eye care professional is mandatory.';
  const splitDisclaimer = doc.splitTextToSize(disclaimer, 190);
  doc.text(splitDisclaimer, 10, 282);

  doc.save(`OCTalyze_Screening_Report_${scan.id}.pdf`);
}
